Step 7: Removed SwiftyJSON dependency
PhyllisWong/EvolvKit pull request #22
Opened 2019-08-15 15:39 UTC by divbyzero

- Removed EvolvRawAllocations.swift
- Added EvolvRawAllocation with tests
- Added EvolvRawAllocationNode with test
- Removed SwiftyJSON from Podfile and podspec
- Updated dependencies and fixed typo in podspec
- Updated EvolvAllocationStore protocol
- Refactored EvolvAllocations class
- Updated TestData in tests

2019-08-15 17:19 UTC, PhyllisWong commented on Example/Example/CustomAllocationStore.swift
>       implementing the store. You can install SwiftyJSON here: https://cocoapods.org/pods/SwiftyJSON.
As SwiftJSON is no longer a dependency, we should update the comments.

2019-08-15 17:34 UTC, PhyllisWong commented on Tests/ExecutionTest.swift
forgot to ask for test that demonstrates the execution supports JSON data type in the last PR. Can this please be added before closing out this PR?

2019-08-15 17:35 UTC, PhyllisWong commented on EvolvKit.podspec
> +  'This SDK is designed to be integrated into projects to allow for autonomous UI optimizations'
👍

2019-08-15 17:37 UTC, PhyllisWong commented on Example/Example/CustomAllocationStore.swift
>       implementing the store. You can install SwiftyJSON here: https://cocoapods.org/pods/SwiftyJSON.
Will also need to update every place that mentions SwiftyJSON.

2019-08-15 17:38 UTC, PhyllisWong commented on Source/EvolvAllocationStore.swift
>       - Returns: a SwiftyJSON array of allocation if one exists, else an empty SwiftyJSON array.
SwiftyJSON comment

2019-08-15 17:45 UTC, PhyllisWong commented on Source/EvolvRawAllocationNode.swift
> +        case dictionary
is case dictionary to support json data type?

2019-08-15 17:52 UTC, PhyllisWong commented on Source/EvolvRawAllocationNode.swift
> +        for key in keyPathKeys {
we will need to be able to drill down to the furthest nested value in a json that could look like = 
{ genome: { ui: { layout: { checkout: { button: { color: "#ffffff", text: "checkout" } , background: { color: "#000000", height: 500 }}}}}. However the json will probably be more complex with more nested values that we will not know in advance. Does this [String: Any] support this?

2019-08-15 17:52 UTC, PhyllisWong commented on Tests/AllocationsTest.swift
>      func test_KeyWithEmptyKeyPart() {
lets add a test that demonstrates json as a data type

2019-08-15 17:54 UTC, PhyllisWong commented on Tests/RawAllocationNodeTest.swift
> +        let jsonString4 = "{\"isPromo\": true, \"demo\": {\"bar\": 50}}"
this is great, but can we add more values that are at least 4 levels nested?

2019-08-15 17:56 UTC, PhyllisWong commented on Tests/RawAllocationTest.swift
> +class RawAllocationTest: XCTestCase {
thank you for adding these tests

2019-08-15 18:00 UTC, PhyllisWong commented on Source/EvolvRawAllocationNode.swift
> +    }
👍

2019-08-15 18:05 UTC, phylliswong requested changes
I left some feedback in the comments. Please review and let me know if there are any questions.

2019-08-15 18:13 UTC, PhyllisWong commented on Example/Example/ViewController.swift
>  import EvolvKit
SwiftyJSON in the doc strings

2019-08-16 16:15 UTC, divbyzero commented on Example/Example/CustomAllocationStore.swift
>       implementing the store. You can install SwiftyJSON here: https://cocoapods.org/pods/SwiftyJSON.
Yep. I'll do it.

2019-08-16 16:15 UTC, divbyzero commented on Tests/ExecutionTest.swift
Foundation doesn't have JSON struct in Swift. So we need to use Foundation objects.

Dictionary -> [String: Any]
Array -> [Any]
Value -> NSString, NSNumber, NSNull

https://developer.apple.com/documentation/foundation/jsonserialization

I'll add tests for [String: Any] and [Any].

2019-08-16 16:16 UTC, divbyzero commented on Tests/RawAllocationNodeTest.swift
> +        let jsonString4 = "{\"isPromo\": true, \"demo\": {\"bar\": 50}}"
I'll add it.

2019-08-16 22:07 UTC, phylliswong approved these changes
these changes look great, thank you for implementing them.

2019-08-16 22:28 UTC, merged